### ISSUE TITLE
Incorrectly trying to determine the IP

### ISSUE THREAD

**Issue by deecewan** [blargity/react-native-schemes-manager#34]
There seems to be a problem with `eval`ing the code [here](https://github.com/blargity/react-native-schemes-manager/blob/master/lib/react-native-xcode.sh#L103). One of my colleagues had his WiFi set up on `en1`, so the first line there was not returning.
The fallback using `ifconfig` does not work because the awk parameters are tried to resolved in the original context (the `'` escape the code from the `eval` from what I can tell).

I'm mostly curious as to why eval is being used in the first place.

### Steps to reproduce the behavior 

- don't have `en0` on your machine (you should probably have an `en1`, or something)
- run `react-native run-ios` (or whatever your relevant command is)

### Expected behavior

- you should get an `IP`, and a `xip` should work correctly.

### Actual behavior

`IP` ends up being empty

**Comment by tmaly1980** [comment]
I noticed this too and have this fixed in https://github.com/blargity/react-native-schemes-manager/pull/38

But someone needs to merge the pull request.

**Comment by henrikra** [comment]
@deecewan This PR is now merged. Can you try the new version if you still have this problem?

**Comment by blargity** [comment]
I'll go ahead and close this issue as I believe it's resolved. If I'm wrong, apologies in advance and please feel free to open a new one.
