### ISSUE TITLE
Trying to debug on ios device, CONFIGURATION is always Release

### ISSUE THREAD

**Issue by jacobbodkin** [blargity/react-native-schemes-manager#42]
Just as the title says, I am trying to create a debug build on a physical device, however no matter what, $CONFIGURATION always is Release

Edit: Now that I double checked, it is always release when building on the simulator as well.

### Steps to reproduce the behavior
1) Create several Debug configurations
2) Try to run on ios device

### Expected behavior
Be able to have the app run in dev mode and debug on physical device

### Actual behavior
App is configured as a production build

**Comment by paintedbicycle** [comment]
I can also confirm that `if (__DEV__) {}` no longer works in my app.

**Comment by paintedbicycle** [comment]
I can also confirm that PR# https://github.com/blargity/react-native-schemes-manager/pull/43 fixes it

**Comment by jacobbodkin** [comment]
@paintedbicycle, after testing #43, I am still getting $CONFIGURATION = Release

**Comment by paintedbicycle** [comment]
Where are you defining that? Xcode Build shell script?

For me, https://github.com/blargity/react-native-schemes-manager/pull/43 fixed using (_DEV_) inside my projects JS. I haven't tested $CONFIGURATION

**Comment by paintedbicycle** [comment]
When I echo ${CONFIGURATION} from inside Xcode build step, I correctly see "App Store" for my app.

**Comment by jacobbodkin** [comment]
I went through and deleted all of my configs (except debug and release) and recreated. Now I am getting the correct $CONFIGURATION. 

Thanks for showing me #43 @paintedbicycle, it worked!
